# Generated by Django 4.2 on 2023-04-26 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_taskmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
