# Generated by Django 4.1.5 on 2023-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_taskmodel_created_at_taskmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
