# Generated by Django 4.1.5 on 2023-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_remove_taskmodel_id_taskmodel_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_id',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
